### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Quezako** [UnknownX7/Cammy#1]
Very good plugin!
I have some features suggestions :
- bind fov change to a command, macro or keybind.
- make some zoom / fov sets based on conditions, like DynamicCam for WoW :
https://www.curseforge.com/wow/addons/dynamiccam

**Comment by UnknownX7** [comment]
Good ideas, I'll see about adding conditions / camera presets using QoLBar when the new Dalamud .net5 update comes out since the plugin IPC is changing.

**Comment by owopeachy** [comment]
I'd love some way of changing the camera's height (esp in 1st person) because lalafell default height is on top of their head instead of eye level. This seems to be the only camera plugin that actually works (i just use it so i can look vertically upwards)

**Comment by UnknownX7** [comment]
If anyone is wondering, I am currently working on rewriting Cammy. Soon:tm:

![image](https://user-images.githubusercontent.com/12263784/139812933-76baecf9-a625-4736-abad-02136fb9a50f.png)

**Comment by owopeachy** [comment]
looking forward to it

**Comment by joerithienpont** [comment]
> If anyone is wondering, I am currently working on rewriting Cammy. Soon™️
> 

Do you think it's possible to automatically change the preset based on the area/instance that your in?

**Comment by UnknownX7** [comment]
It will be possible to do any condition that QoLBar supports (area is one of them). The plugin will behave similarly to before without QoLBar installed, but will gain access to conditions to allow automatic changes if it is. This way I don't have to maintain two copies of the same system and questions about how to create one can be asked in the plugin Discord without breaking the third party rule.

**Comment by UnknownX7** [comment]
✔️
