### ISSUE TITLE
Automatic Zooming IN

### ISSUE THREAD

**Issue by Srycnthearu** [UnknownX7/Cammy#2]
Hey, I wanted to say that this plugin is amazing, but I've come across a very annoying issue. I have set the FOV in FFXIV but every time I go to a merchant and exit the merchants menu the game changes my FOV and zooms in effectively making the plugin not work anymore. I need to then manually go back into the plugin settings and select the profile I've made in order for it to work again. 

Is there a way you can code something to lock the camera to my settings without it ever being able to be changed? OR if you can add a setting that allows you to map your settings to a specific key on the keyboard that you can hit to retune your FOV to the setting of the app that would be GREAT! Is this possible?

**Comment by Srycnthearu** [comment]
or maybe I'm setting the settings wrong?

**Comment by Maxunit** [comment]
Tried it as well and can confirm. Added FOV values get reset (but not visually in the config menu) after talking to a Vendor.

**Comment by UnknownX7** [comment]
Is it just added fov that gets reset? Try just adding the desired amount to both min and max. I'll have to block the game from resetting it in that one instance but there's no way to do this automatically without just constantly overwriting the camera every frame which I would like to avoid since it can cause other issues.

**Comment by Maxunit** [comment]
I only tested it in this one specific case so far, but yes, it is "Added FoV". Cammy still reports it being set to the given value, but it actually resets upon exiting the vendor menu.

**Comment by Srycnthearu** [comment]
Thanks for the quick reply guys! I will try setting the min and max and see what happens. Should I set the min and max to the same amount so that it never changes? Like 0.89345 since that’s the added FOV I like?

**Comment by Srycnthearu** [comment]
![CCF51438-D313-4068-A26E-CC30A6F987AB](https://user-images.githubusercontent.com/93870891/140672772-c07de307-b846-4766-8477-2a1d85784cc4.jpeg)
 There are the settings I just tried. Whenever I change the min and max fov I don’t really see a change in the fov. It’s only when I changed added fov do I see a change. I tried making the min and max fov the same but when I leave a merchant it still zooms in.  Are my settings wrong?

**Comment by Srycnthearu** [comment]
I basically am trying to get a really wide fov like I’m watching a widescreen movie to see as much of the world while still having it realistic especially from first person.

**Comment by UnknownX7** [comment]
Change max fov and starting fov to 1.38 and set added fov to 0, also max out fov delta so you can still zoom into first person quickly. Alternatively, if you don't want zooming to change fov you can just make minimum fov 1.38 as well.

**Comment by Srycnthearu** [comment]
Ok 👍🏽 I will try those settings. I really appreciate all the help!!!

**Comment by Srycnthearu** [comment]
THOSE settings WORKED!! It doesn’t zoom in anymore after I exit the merchant!! THANKS SOO MUCH!! 😊😊😊

**Comment by UnknownX7** [comment]
Swapped out added FoV with (holdable) buttons to increment all zoom and FoV values to avoid conflicts with the game.

**Comment by Srycnthearu** [comment]
Do you mean the buttons will now hold the zoom and fov in place regardless?

**Comment by Srycnthearu** [comment]
Do I have to download the new file or will it update automatically?

**Comment by UnknownX7** [comment]
If you don't have the option enabled to update plugins automatically, you will have to update it through the plugin installer. The buttons will just increment all values evenly like Added FoV essentially did before, except the other values don't get overwritten by the game.

**Comment by Srycnthearu** [comment]
GREAT! It works PERFECTLY now! I just want to thank you SOO SOO much! I'm playing FFXIV on an HTC Vive on a Virtual GIANT Theater sized curved screen and so the greater FOV really looks beautiful with this giant screen! THANK YOU once again! You are awesome!
