### ISSUE TITLE
Cammy points at the ground when going into Freecam

### ISSUE THREAD

**Issue by TheePhrog** [UnknownX7/Cammy#21]
for some reason Cammy just looks at the ground, I can make it move around a little bit but is generally stuck looking at the dirt

**Comment by Kumicoo** [comment]
yesame

**Comment by xGeekpower** [comment]
oh so this a 6.2 thing, was wondering If I had press a wrong key and locked it somehow.

**Comment by BleuMage** [comment]
Good to know it's not just me. lol I'll wait for a fix.

**Comment by Nox13last** [comment]
I have this issue as well.
While it's not really a "fix", if you **SIT DOWN**, the camera functions as it should. 
If you can't do this, then go to Cammy's "Other Settings", make sure Free Cam is checked, and then set the mystery slider to "0". That will also work, but WASD movement will be inverted.

**Comment by AeGhBrA** [comment]
Initiating freecam normally, while standing, tilts the camera towards the ground and locks _vertical_ rotation (there's a tiny bit of wiggle room, but mostly locked towards the ground); this previously happened when clicking on an npc or something while in gpose, but now it's reversed.

I've run some tests, and here's some **workarounds** that I found:

- enabling freecam while **sitting** (ground, chair) allows for normal controls, however this is useless for gposers (can't sit up again for the animation you were going for initially)
- clicking on an npc in gpose while the bugged freecam is enabled restores normal functionality, until you click on the ground (so it resets to your own character)
- while in the bugged freecam, opening the **configuration** and pressing the **"default" button** (circular arrow) next to any slider will return normal movement/rotation • this will not work with text commands like _/cammy fov 90_ or w/e, just from the UI (if you can't see the configuration window in gpose, untick [Hide plugin UI while gpose is active] in **Dalamud Settings** > **Look & Feel** tab) — _however_ this also makes the camera wheel zoom like normal when adjusting speed; other keys stay normal, but mousewheel is affected — the workaround to this is to adjust the speed to your liking and then press the keyboard's zoom button (PgUp default?) to get back to a normal position —— in addition to the mousewheel zooming, the camera also orbits around a point, the rotation is not centered on the camera itself (as it would be in first person mode) but on what would be your character - and you can't zoom in further; the 0-1 slider toggles this but controls get reversed when it's 0
- normal functionality can also be restored by enabling freecam then ticking and unticking the Delimit checkbox in Anamnesis (camera controls only possible from gpose though)

It seems the camera being stuck looking down is a problem of zoom; if you enable freecam while in gpose, go to Anamnesis and try moving the slider for Zoom: it will reset to 0.1, which locks the rotation. — ticking Delimit now allows you to change the zoom, allowing normal movement (with the standard pivot/orbit around what would be the player); changing zoom to 0.1 makes the camera behave like the bug — unticking Delimit (while the zoom was set to 0.1) will now make the camera behave like it did before - but only ticking+unticking delimit will do the same thing, me playing around with the zoom was only to find what's causing the rotation bug.
