### ISSUE TITLE
unable to install the newly update

### ISSUE THREAD

**Issue by Anpoe** [UnknownX7/Cammy#24]
HI, 
I have been using this plugin for a long time and quite like how it makes my life easier, but currently, the new update for Chinese player to 6.11 just disable this plugin to work (after I click the update all button on Dalamud... That was a mistake), I wonder if you have an older vision of this plugin that I can install？

**Comment by UnknownX7** [comment]
https://github.com/UnknownX7/DalamudPluginRepo/raw/682611960c0b0081de8c4e5a1f4e07ff2f42819c/plugins/Cammy/latest.zip
