### ISSUE TITLE
Proper FreeCam support for GPose?

### ISSUE THREAD

**Issue by Maxunit** [UnknownX7/Cammy#3]
Heyo UnknownX,

FreeCam currently works flawlessly during normal gameplay, but are there plans to have it working properly in GPose as well? (Camera movement is "borked" right now in GPose)

Cheers,

Maxunit

**Comment by UnknownX7** [comment]
Probably a bit too much work to do properly for not much reward, unfortunately. As a workaround you can now lock the camera in position before going into /gpose, which should solve some issues with it.

**Comment by Chirality1349** [comment]
hey hey Unknown, i worked much with cammy in GPose, but since a week i cant use cammy anymore in it, then i go into free cam i cant open gpose anymore, any help for this?

greetings
