### ISSUE TITLE
Presets don't autoswitch based on QoLBar presets

### ISSUE THREAD

**Issue by willkydd** [UnknownX7/Cammy#33]
I have a QoLBar preset defined by conditionflag = occupiedinquestevent. I associated it to a cammy preset but cammy doesn't switch to it automatically. qolbar is detected.

**Comment by UnknownX7** [comment]
It may be that a preset higher in the list is overriding it, Cammy will attempt to use the highest preset that the condition set is true for (or doesn't exist). Could you show a picture of how your presets are ordered?

**Comment by willkydd** [comment]
Yes, it was an override issue. Switched the profile order and put the default at the bottom and now it all works as intended.

Thanks!
