### ISSUE TITLE
Controller support + player movement possible in Free-CAM?

### ISSUE THREAD

**Issue by TranquilPicture** [UnknownX7/Cammy#4]
This feature is absolutely amazing for cinematography! It's something of a dream come true when it comes to creative framing in story telling.

Controller support exists insofar as being able to rotate the camera, but also being able to navigate with the left analog stick would be lovely. I ask since controller movement and panning can allow from smoother and more dynamic presentation. I sincerely hope this is implementable!

As a quick aside, would it at all be possible to switch back to character movement whilst still within free-cam mode? This would open up many possibilities!

Thank you for all the hard work. It's greatly appreciated.

**Comment by UnknownX7** [comment]
I'll have to look into how the game processes controller inputs, as for moving during free cam, it is currently unreleased, but will be in the next version. bbfc8dde221c03bc676438e03e3728e247e1f61c
