### ISSUE TITLE
Tilt slider dissapeared

### ISSUE THREAD

**Issue by GunB** [UnknownX7/Cammy#40]
I really loved this function to tilt the camera for more precise pictures as the slider and editing manually the value really gave a lot of power to precission. Is it possible to bring this function back to cammy?

Thank you for the hard work and amazing plugin.

**Comment by UnknownX7** [comment]
Sorry about that, I've gone ahead and put it back in the "Other Settings" tab for the time being since it didn't make much sense for presets.

**Comment by GunB** [comment]
Well, the presets was nice be ause I could have multiple camera angles pre-made so I just had to load them in. It was really nice to have it there to reuse those angles easily.
Thank you for adding the feature again! Although if possible would love to have it back into the presets so the pre-made camera angles are saved with all it's configurations.

Thank you for the quick response and amazing work

**Comment by UnknownX7** [comment]
Did you only use the presets for the tilt? If so, I could add a subcommand for quickly changing to specific tilt values. I'd rather keep it out of presets if possible just because there's so much that resets it.

**Comment by GunB** [comment]
I had this and other configs so the shot would stay still and would be easy to pick up. I can't remember all the options I had but I remember changing anything would reset my camera but by adjusting the default soon, the shot was saved properly how I wanted it.

**Comment by UnknownX7** [comment]
I've restored it to the current presets until a later update implements presets meant for screenshots and videos (no ETA yet).
