### ISSUE TITLE
Is the current plugin version not working?

### ISSUE THREAD

**Issue by ElverDulero735** [UnknownX7/Cammy#41]
The plugins window says:
"Download failed (https://github.com/UnknownX7/Cammy.git)" in red color, and obviously it doesnt show Cammy on the plugin installer so I cant really install it, anybody knows how to fix it?

**Comment by UnknownX7** [comment]
Change the custom repository URL in Dalamud's settings from `https://github.com/UnknownX7/Cammy.git` to `https://raw.githubusercontent.com/UnknownX7/DalamudPluginRepo/master/pluginmaster.json`
