### ISSUE TITLE
about isInputIDHeld

### ISSUE THREAD

**Issue by tssailzz8** [UnknownX7/Cammy#5]
hello,i use it in game,and i want to use other key. but i don not konw what int to the congifkey.can you tell me?

**Comment by UnknownX7** [comment]
Unfortunately, I haven't RE'd how to get a name for them, I was just using https://github.com/UnknownX7/Cammy/blob/master/Game.cs#L168-L172 and pressing the button to find them. There's also many bindings for each button so you'll have to rebind it to find the correct one. Additionally, a few of the bindings can only be held for some reason.
