### ISSUE TITLE
Request: slash command to enter freecam

### ISSUE THREAD

**Issue by zhongjiedong** [UnknownX7/Cammy#50]
Just that /freecam or something so I can put it on QoL bar

**Comment by frukbachers** [comment]
Would be nice as well. I only have one camera preset personally zooming a bit more out, otherwise I just like to explore out of bounds areas or look at npc/s people up close without me walking awkwardly around them

**Comment by UnknownX7** [comment]
This is already possible, you can use `/cammy freecam` to enter it.
