### ISSUE TITLE
7.0 DT Update

### ISSUE THREAD

**Issue by Gasteno** [UnknownX7/Cammy#53]
Hi there and thanks for all of the great plugins you have provided the community. Any plans to update this plugin? We are grateful.

**Comment by UnknownX7** [comment]
Certain bug fixes and features are currently broken due to internal changes, I don't have an ETA for these being fixed as they will require new workarounds. I will likely release a partial Dawntrail update within 24h assuming no major issues are found.

**Comment by PluginTamperer** [comment]
I believe I saw somewhere that you had a temporary fix for cammy, but I can't figure out how to install it on my end.

**Comment by Sunflowertism** [comment]
> I believe I saw somewhere that you had a temporary fix for cammy, but I can't figure out how to install it on my end.

I saw that too but was also confused on how to access any files to make it work.  Would really help my vertigo to have this one working again.

**Comment by Sunflowertism** [comment]
> Certain bug fixes and features are currently broken due to internal changes, I don't have an ETA for these being fixed as they will require new workarounds. I will likely release a partial Dawntrail update within 24h assuming no major issues are found.

It's working again, bless you
