### ISSUE TITLE
Disable forced camera movement/boundries when interacting with target

### ISSUE THREAD

**Issue by weiler-git** [UnknownX7/Cammy#62]
When talking or interacting with a target, the game would normally tilt the camera, and force it within certain boundries.
Would it be possible to remove this?
I don't want the game to tilt or move my camera at all when interacting, and i want to be allowed to rotate outside boundries.
I found this to be very annoying, would highly appreciate if its possible.

**Comment by cactuschef3** [comment]
this is a base game feature, go to character config -> bottom of the first page -> uncheck 'look at target when speaking'

**Comment by weiler-git** [comment]
It really is in the game, and I been hating not having it for so many years.... 
Thank you cactuschef3!

**Comment by weiler-git** [comment]
base game feature
