### ISSUE TITLE
Latest update causes problems with Anamnesis.

### ISSUE THREAD

**Issue by Maxunit** [UnknownX7/Cammy#7]
I am just reporting this here as well, just in case.

Earlier versions of Cammy did not cause any problems, but I noticed, that the latest update for Cammy somehow creates a conflict with Anamnesis. As soon as Cammy is installed, Anamnesis can no longer modify the X Y Z values (Angle etc pp still works).

**Comment by UnknownX7** [comment]
Is this possibly caused by an issue with loading Cammy after Anamnesis? The latest update should not have changed anything.

**Comment by Maxunit** [comment]
Oh no, I can start Ana way after I already started playing FFXIV with Cammy enabled.
I have no idea why it is happening, but I downloaded the code from the 9858fc8 branch and that one works fine again.
I will look a bit more into it, tho.

**Comment by UnknownX7** [comment]
Can you check if this commit still works? https://github.com/UnknownX7/Cammy/commit/db9c9699d04c283e252fa108ffd7beccf221b3fd
